services:
  - type: web
    name: uma-draft-tool
    runtime: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install setuptools
      pip install -r requirements.txt
    startCommand: gunicorn -k eventlet -w 1 app:app